[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/api/attributes"
  to = "https://exist.io/api/1/users/$self/attributes/?limit=10&attributes=steps,heartrate,caffeine,tracks,weather_summary,weather_temp_max,weather_temp_min"
  status = 200
  force = true
  headers = {Authorization = "Token $EXIST_TOKEN"}
